kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-obspfs
  annotations:
    everest.io/obs-volume-type: STANDARD
    csi.storage.k8s.io/fstype: obsfs

spec:
  storageClassName: csi-obs
  # storageClassName: gp2
  # storageClassName: local-storage
  # storageClassName: ibmc-block-bronze
  # storageClassName: ibmc-block-silver
  # storageClassName: ibmc-block-gold
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench-obspfs
spec:
  template:
    spec:
      containers:
      - name: dbench-obspfs
        image: tellmenop/dbench:5.0
        imagePullPolicy: IfNotPresent
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          # - name: DBENCH_QUICK
          #   value: "yes"
          # - name: FIO_SIZE
          #   value: 1G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "0"
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: dbench-obspfs
  backoffLimit: 4
